### ISSUE TITLE
regression in 1.8.0, relation "integer" does not exist

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#1015] opened 2021-05-13 04:10 UTC
The following query to enumerate IP addresses compiles correctly on 1.7.0, but fails on 1.8.0 and tip:

```sql
-- name: Test180Regression :many
SELECT (@gw_address::inet) + i
FROM generate_series(0, @end_series::int) AS i
LIMIT 1;
```

```
db/query/ips.sql:1:1: relation "integer" does not exist
```

**Comment by kyleconroy** [comment] 2021-05-16 00:05
Duplicate of #1004

**Closed by kyleconroy** 2021-05-16 00:05 UTC
