### ISSUE TITLE
SQLITE: cannot create STRICT tables

### ISSUE THREAD

**Issue by capnspacehook** [kyleconroy/sqlc#1896] opened 2022-10-13 16:46 UTC
### Version

1.15.0

### What happened?

I tried to create a SQLITE table with the `STRICT` option as described here: https://www.sqlite.org/stricttables.html

This shouldn't affect `sqlc` behavior at all, I imagine the parser will just have to learn to parse and ignore a properly placed `STRICT` keyword.

### Relevant log output

```shell
line 6:2 extraneous input 'STRICT' expecting {<EOF>, ';', ALTER_, ANALYZE_, ATTACH_, BEGIN_, COMMIT_, CREATE_, DEFAULT_, DELETE_, DETACH_, DROP_, END_, EXPLAIN_, INSERT_, PRAGMA_, REINDEX_, RELEASE_, REPLACE_, ROLLBACK_, SAVEPOINT_, SELECT_, UPDATE_, VACUUM_, VALUES_, WITH_}
# package db
query.sql:1:1: extraneous input 'STRICT' expecting {<EOF>, ';', ALTER_, ANALYZE_, ATTACH_, BEGIN_, COMMIT_, CREATE_, DEFAULT_, DELETE_, DETACH_, DROP_, END_, EXPLAIN_, INSERT_, PRAGMA_, REINDEX_, RELEASE_, REPLACE_, ROLLBACK_, SAVEPOINT_, SELECT_, UPDATE_, VACUUM_, VALUES_, WITH_}
```

### Playground URL

https://play.sqlc.dev/p/3a11b31aadf5afba92e0a1e84c43debfa2e4f3eb6bc46e614e2f8cf2d2ba3a99

### What operating system are you using?

Linux

### What type of code are you generating?

Go

**Comment by rosszurowski** [comment] 2022-10-17 15:20
Seems like this is a duplicate of https://github.com/kyleconroy/sqlc/issues/1877, which was filed earlier.

**Comment by capnspacehook** [comment] 2022-10-17 22:51
Thanks, closing in favor of that issue then

**Closed** 2022-10-17 22:51 UTC
Labels: bug, triage
