### ISSUE TITLE
PostgreSQL substring() detect as wrong type

### ISSUE THREAD

**Issue by jamesli2021** [kyleconroy/sqlc#1487] opened 2022-03-15 17:44 UTC
### Version

1.12.0

### What happened?

Found a bug.

PostgreSQL 14.1:
... SUBSTRING(title, 1, 10) ...

sqlc struct:
Title         []byte `json:"title"`

Could this be fix as string instead of detected as []byte data type?

### Relevant log output

```shell
See above
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment] 2022-03-19 02:42
Duplicate of #1450

**Closed by kyleconroy** 2022-03-19 02:42 UTC
Labels: bug, :books: postgresql, :wrench: golang, :computer: darwin
