### ISSUE TITLE
Fields not nullable when INNER JOINing to a LEFT JOIN

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#604] opened 2020-07-21 18:29 UTC
This contrived example:
```sql
CREATE TABLE users (
  user_id    INT PRIMARY KEY,
  city_id    INT -- nullable
);
CREATE TABLE cities (
  city_id    INT PRIMARY KEY,
  mayor_id   INT NOT NULL
);
CREATE TABLE mayors (
  mayor_id   INT PRIMARY KEY,
  full_name  TEXT NOT NULL
);

-- name: GetMayors :many
SELECT
    user_id,
    mayors.full_name
FROM users
LEFT JOIN cities USING (city_id)
INNER JOIN mayors USING (mayor_id);
```

Produces this results struct:
```go
type GetMayorsRow struct {
	UserID   int32
	FullName string
}
```

Running this query will fail if `city_id` is `NULL`. Because of the left join, the correct type for `FullName` is `sql.NullString`.

**Comment by davherrmann** [comment] 2020-10-11 17:30
This might be a duplicate of #374? Just ran into this when doing a `FULL JOIN`.

**Comment by jwilner** [comment] 2021-04-26 14:04
Outer joins definitely aren't supported yet, but `mayors.full_name` shouldn't be null with the provided query.

```
mysql> SELECT * FROM users;
+---------+---------+
| user_id | city_id |
+---------+---------+
|       1 |    NULL |
|       2 |       1 |
+---------+---------+
2 rows in set (0.00 sec)

mysql> SELECT * FROM mayors;
+----------+-----------+
| mayor_id | full_name |
+----------+-----------+
|        1 | bob       |
+----------+-----------+
1 row in set (0.00 sec)

mysql> SELECT * FROM cities;
+---------+----------+
| city_id | mayor_id |
+---------+----------+
|       1 |        1 |
+---------+----------+
1 row in set (0.00 sec)

mysql> SELECT
    ->     user_id,
    ->     mayors.full_name
    -> FROM users
    -> LEFT JOIN cities USING (city_id)
    -> INNER JOIN mayors USING (mayor_id);
+---------+-----------+
| user_id | full_name |
+---------+-----------+
|       2 | bob       |
+---------+-----------+
1 row in set (0.00 sec)

mysql> SELECT
    ->     user_id,
    ->     mayors.full_name
    -> FROM users
    -> LEFT JOIN cities USING (city_id)
    -> LEFT JOIN mayors USING (mayor_id);
+---------+-----------+
| user_id | full_name |
+---------+-----------+
|       1 | NULL      |
|       2 | bob       |
+---------+-----------+
2 rows in set (0.00 sec)
```

**Comment by jwilner** [comment] 2021-04-26 14:07
Please see https://github.com/kyleconroy/sqlc/pull/983 for WIP on proper support.

**Comment by fr3fou** [comment] 2021-06-21 18:34
Should this be closed, seeing as #983 fixed it?

**Closed** 2021-08-28 21:18 UTC
Labels: bug

**Comment by davherrmann** [comment] 2022-03-01 08:36
I just stumbled upon this again. The example still produces the incorrect type, see [this playground link.](https://play.sqlc.dev/p/eb2456ca821eb8159be0c50393df636d4915d1dd5f2564163a879119e5b03c4b)

Could we maybe reopen the issue?

**Comment by GuillaumeDesforges** [comment] 2025-01-10 14:32
Same issue, with a inner join followed by left joins.
