### ISSUE TITLE
install failed, prompt wasmtime library not found

### ISSUE THREAD

**Issue by rocky114** [kyleconroy/sqlc#1878] opened 2022-10-04 09:33 UTC
### Version

1.15.0

### What happened?

MacBook Air (M1, 2020) macOS Big Sur 11.6 (20G165)

expect install success

### Relevant log output

```shell
brew install wasmtime

huangdongcheng@rocky114 0.30.0 % pwd
/opt/homebrew/Cellar/wasmtime/0.30.0
huangdongcheng@rocky114 0.30.0 % ls -al
total 64
drwxr-xr-x  9 huangdongcheng  admin    288 Oct  4 17:05 .
drwxr-xr-x  3 huangdongcheng  admin     96 Oct  4 17:05 ..
drwxr-xr-x  3 huangdongcheng  admin     96 Sep 18  2021 .brew
-rw-r--r--  1 huangdongcheng  admin    101 Sep 18  2021 .crates.toml
-rw-r--r--  1 huangdongcheng  admin    402 Sep 18  2021 .crates2.json
-rw-r--r--  1 huangdongcheng  admin    917 Oct  4 17:05 INSTALL_RECEIPT.json
-rw-r--r--  1 huangdongcheng  admin  12243 Sep 18  2021 LICENSE
-rw-r--r--  1 huangdongcheng  admin   4965 Sep 18  2021 README.md
drwxr-xr-x  3 huangdongcheng  admin     96 Sep 18  2021 bin
huangdongcheng@rocky114 0.30.0 % 

I can't fond lib or include dir, then exec install command, prompt failed.

go install github.com/kyleconroy/sqlc/cmd/sqlc@latest

# github.com/bytecodealliance/wasmtime-go
ld: library not found for -lwasmtime
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

**Comment by kyleconroy** [comment] 2022-11-09 05:54
```
go install -tags=nowasm github.com/kyleconroy/sqlc/cmd/sqlc@latest
```

Duplicate of https://github.com/kyleconroy/sqlc/issues/1848

**Closed by kyleconroy** 2022-11-09 05:54 UTC
Labels: bug, triage
