### ISSUE TITLE
generate files in 3 different packages

### ISSUE THREAD

**Issue by MS-24** [kyleconroy/sqlc#1976] opened 2022-12-01 10:52 UTC
This might be similar to #1951

I would need structure my project to separate db, model and service
But sqlc generates 3 files in a single output path under same package . 
Is there a way I could configure 3 different package names for 3 different files.
Something similar to out file name 
"
     output_db_file_name: "db.go"
    output_models_file_name: "models.go"
    output_querier_file_name: "querier.go"
"
Can we have like below ?
     db_package: "db"
    models_package: "models"
    service_package: "service"

Thanks!!

**Comment by kyleconroy** [comment] 2023-02-22 21:07
Closing as a duplicate of https://github.com/kyleconroy/sqlc/issues/1941

**Closed by kyleconroy** 2023-02-22 21:07 UTC
