### ISSUE TITLE
"go get" broken out of the box

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#791] opened 2020-11-17 22:01 UTC
A colleague is attempting to install with "GO111MODULE=on go get github.com/kyleconroy/sqlc/..." and getting Offset syntax errors

**Comment by kevinburkemeter** [comment] 2020-11-18 16:52
Here's what we see when we try to do it

```
$ go install github.com/kyleconroy/sqlc/cmd/sqlc
# github.com/lfittl/pg_query_go/parser
pg_query_parse_plpgsql.c: In function ‘pg_query_parse_plpgsql’:
pg_query_parse_plpgsql.c:437:10: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
  437 |    (void)asprintf(&new_out, "%s%s,\n", result.plpgsql_funcs, func_json);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# github.com/kyleconroy/sqlc/internal/engine/dolphin
go/src/github.com/kyleconroy/sqlc/internal/engine/dolphin/convert.go:302:28: n.OldTable undefined (type *"github.com/pingcap/parser/ast".RenameTableStmt has no field or method OldTable)
go/src/github.com/kyleconroy/sqlc/internal/engine/dolphin/convert.go:303:29: n.NewTable undefined (type *"github.com/pingcap/parser/ast".RenameTableStmt has no field or method NewTable)
```

**Comment by kyleconroy** [comment] 2020-11-18 17:32
Duplicate of https://github.com/kyleconroy/sqlc/issues/654

**Closed by kyleconroy** 2020-11-18 17:32 UTC
Labels: duplicate
