### ISSUE TITLE
On macOS Monterey go test ./... is not working

### ISSUE THREAD

**Issue by thinkofher** [kyleconroy/sqlc#1889] opened 2022-10-08 16:45 UTC
### Version

Other

### What happened?

Hello sqlc contributors 👋 !

I was about to start hacking on sqlc, because it lacks some sqlite features that I need. Unfortunately I was unable to run tests. Probably because of some issues with C linker and postgresql parser (I'm not really experienced in that field, its just first assumption).

Have anyone here run into similar issues? 

I've pasted `go test ./...` below.

btw, for anyone who is also somehow blocked because of this issue, on linux everything works great. You can still use docker to run sqlc.

    $ docker run --rm -it -v $(pwd):/app golang:1.19 sh -c "cd /app; go generate ./..."

### Relevant log output

```shell
?   	github.com/kyleconroy/sqlc	[no test files]
# github.com/pganalyze/pg_query_go/v2/parser
In file included from gram.y:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/postgres.h:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/c.h:1330:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/port.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:91:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netinet/in.h:81:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:425:1: error: expected ';' after top level declarator
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:587:101: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPES'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:580:2: note: expanded from macro '\
__CCT_DECLARE_CONSTRAINED_PTR_TYPE'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:548:2: note: expanded from macro '__CCT_DISPATCH'
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:113:26: note: expanded from macro '__CONCAT'
<scratch space>:415:1: note: expanded from here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:563:14: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPE_3'
In file included from gram.y:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/postgres.h:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/c.h:1330:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/port.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:91:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netinet/in.h:81:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:425:1: error: expected ';' after top level declarator
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:588:101: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPES'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:580:2: note: expanded from macro '\
__CCT_DECLARE_CONSTRAINED_PTR_TYPE'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:548:2: note: expanded from macro '__CCT_DISPATCH'
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:113:26: note: expanded from macro '__CONCAT'
<scratch space>:420:1: note: expanded from here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:567:11: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPE_4'
In file included from gram.y:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/postgres.h:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/c.h:1330:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/port.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:91:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netinet/in.h:81:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:471:1: error: typedef redefinition with different types ('struct sockaddr_storage *' vs 'struct sockaddr *')
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:587:101: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPES'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:580:2: note: expanded from macro '\
__CCT_DECLARE_CONSTRAINED_PTR_TYPE'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:548:2: note: expanded from macro '__CCT_DISPATCH'
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:540:38: note: expanded from macro '__CCT_CONTRACT_TO_ATTR'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:113:26: note: expanded from macro '__CONCAT'
<scratch space>:429:1: note: expanded from here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:425:1: note: previous definition is here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:588:101: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPES'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:580:2: note: expanded from macro '\
__CCT_DECLARE_CONSTRAINED_PTR_TYPE'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:548:2: note: expanded from macro '__CCT_DISPATCH'
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:540:38: note: expanded from macro '__CCT_CONTRACT_TO_ATTR'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:113:26: note: expanded from macro '__CONCAT'
<scratch space>:421:1: note: expanded from here
In file included from gram.y:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/postgres.h:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/c.h:1330:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/port.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:91:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netinet/in.h:81:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:471:1: error: expected ';' after top level declarator
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:587:101: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPES'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:580:2: note: expanded from macro '\
__CCT_DECLARE_CONSTRAINED_PTR_TYPE'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:548:2: note: expanded from macro '__CCT_DISPATCH'
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:113:26: note: expanded from macro '__CONCAT'
<scratch space>:428:1: note: expanded from here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:563:14: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPE_3'
In file included from gram.y:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/postgres.h:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/c.h:1330:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/port.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:91:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netinet/in.h:81:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:471:1: error: typedef redefinition with different types ('struct sockaddr_storage *' vs 'struct sockaddr *')
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:588:101: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPES'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:580:2: note: expanded from macro '\
__CCT_DECLARE_CONSTRAINED_PTR_TYPE'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:548:2: note: expanded from macro '__CCT_DISPATCH'
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:540:38: note: expanded from macro '__CCT_CONTRACT_TO_ATTR'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:113:26: note: expanded from macro '__CONCAT'
<scratch space>:6:1: note: expanded from here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:425:1: note: previous definition is here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:588:101: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPES'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:580:2: note: expanded from macro '\
__CCT_DECLARE_CONSTRAINED_PTR_TYPE'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:548:2: note: expanded from macro '__CCT_DISPATCH'
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:540:38: note: expanded from macro '__CCT_CONTRACT_TO_ATTR'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:113:26: note: expanded from macro '__CONCAT'
<scratch space>:421:1: note: expanded from here
In file included from gram.y:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/postgres.h:46:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/c.h:1330:
In file included from ../../../../go/pkg/mod/github.com/pganalyze/pg_query_go/v2@v2.1.2/parser/include/port.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:91:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netinet/in.h:81:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:471:1: error: expected ';' after top level declarator
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:588:101: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPES'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:580:2: note: expanded from macro '\
__CCT_DECLARE_CONSTRAINED_PTR_TYPE'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:548:2: note: expanded from macro '__CCT_DISPATCH'
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:113:26: note: expanded from macro '__CONCAT'
<scratch space>:5:1: note: expanded from here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:567:11: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPE_4'
ok  	github.com/kyleconroy/sqlc/internal/codegen/golang	0.606s
ok  	github.com/kyleconroy/sqlc/internal/codegen/sdk	0.455s
ok  	github.com/kyleconroy/sqlc/internal/config	0.711s
FAIL	github.com/kyleconroy/sqlc/internal/endtoend [build failed]
FAIL	github.com/kyleconroy/sqlc/internal/engine/postgresql [build failed]
ok  	github.com/kyleconroy/sqlc/internal/engine/sqlite	0.974s
ok  	github.com/kyleconroy/sqlc/internal/metadata	0.272s
ok  	github.com/kyleconroy/sqlc/internal/migrations	0.368s
ok  	github.com/kyleconroy/sqlc/internal/python/printer	0.824s
ok  	github.com/kyleconroy/sqlc/internal/source	0.975s
ok  	github.com/kyleconroy/sqlc/internal/sql/named	0.969s
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by thinkofher** [comment] 2022-10-08 16:48
I'm using macOS Monterey 12.6 (Apple M1).

    $ cc --version
    Apple clang version 14.0.0 (clang-1400.0.29.201)
    Target: arm64-apple-darwin21.6.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by christeredvartsen** [comment] 2022-10-10 10:04
After a re-install of Xcode Command Line Tools the generate command seems to be working again.

**Comment by kyleconroy** [comment] 2022-10-12 04:04
@christeredvartsen Looks like we have a workaround for now, closing.

**Closed by kyleconroy** 2022-10-12 04:04 UTC
Labels: bug, triage

**Comment by sgreene570** [comment] 2022-10-18 20:05
Can confirm that the following work around worked for me (albeit it felt very sketchy!)

https://apple.stackexchange.com/questions/93573/how-to-reinstall-xcode-command-line-tools

**Comment by ulfmagnetics** [comment] 2022-11-03 18:45
You can also install the Command Line Tools for XCode 13.4, available via [Apple's download page](https://developer.apple.com/download/all/?q=for%20Xcode). This version include clang v13.1.6, which does not have this compilation issue.

**Comment by lfittl** [comment] 2022-11-04 02:48
I believe this should be fixed by https://github.com/kyleconroy/sqlc/pull/1921

**Comment by funny-falcon** [comment] 2022-11-08 07:40
The problem is in bison: native MacOS bison is very old (2.2). It defines a lot of garbage macroses before include directives.

Instalation of bison 3.8.2 with brew fixed compilation.
