### ISSUE TITLE
create or replace trigger is not working

### ISSUE THREAD

**Issue by zmitry** [kyleconroy/sqlc#1656] opened 2022-06-01 11:59 UTC
### Version

1.13.0

### What happened?

create or replace syntax is not supported

https://play.sqlc.dev/p/17df8d91cece0346e3a8169c77c69129250156ce0cd31055631fcf8357c4b37c

### Playground URL

https://play.sqlc.dev/p/17df8d91cece0346e3a8169c77c69129250156ce0cd31055631fcf8357c4b37c

**Comment by kyleconroy** [comment] 2022-06-04 15:04
The CREATE OR REPLACE TRIGGER syntax was added in PostgreSQL 14. The parser sqlc uses is still based on PostgreSQL 13.

https://github.com/pganalyze/libpg_query/issues/127

**Comment by kyleconroy** [comment] 2022-06-12 17:40
Duplicate of https://github.com/kyleconroy/sqlc/issues/1246

**Closed by kyleconroy** 2022-06-12 17:40 UTC
Labels: :books: postgresql, upstream
