### ISSUE TITLE
JSON Parser fails for type override on complex package names

### ISSUE THREAD

**Issue by rupertevill** [kyleconroy/sqlc#255] opened 2020-01-10 09:59 UTC
The standard syntax for defining a type override in the lib at the moment is:

` "overrides": [
      {
          "go_type": "github.com/gofrs/uuid.UUID",
          "postgres_type": "uuid"
      }
  ]`

This results in the following import statement and type (in the struct) in the auto gen code:

```
import (
    "github.com/gofrs/uuid"
)

type test struct {
    columnOne uuid.UUID
}
```
However, the parser fails if the package name containing the desired type override is more complex, for example "gopkg.in/guregu/null.v3".

Have looked at the parser as it is at the moment and the bug fix doesn't look to bad, let me if you want any contribution 👍

**Comment by Maxiride** [comment] 2020-04-26 09:36
I've closed #462 since I'm pretty sure it was a duplicate issue.
Is the bug caused by the presence of a dot in the package name?

**Comment by rupertevill** [comment] 2020-04-26 12:17
> I've closed #462 since I'm pretty sure it was a duplicate issue.
> 
> Is the bug caused by the presence of a dot in the package name?

Correct. The presence of the dot in the package name causes the issue.

**Comment by Maxiride** [comment] 2020-04-26 13:23
Too bad... those packages are my holy grail.

Anyway,
>Have looked at the parser as it is at the moment and the bug fix doesn't look to bad, let me if you want any contribution 👍

@rupertevill did you eventually started working on a PR?

**Comment by kyleconroy** [comment] 2020-11-15 04:08
This has been fixed in main and will be released in the next version. Here's what it looks like:

```json
{
  "version": "1",
  "packages": [
    {
      "path": "go",
      "name": "override",
      "engine": "postgresql",
      "schema": "schema.sql",
      "queries": "query.sql",
      "overrides": [
        {
          "column": "foo.bio",
          "nullable": true,
          "go_type": {
            "import": "gopkg.in/guregu/null.v4",
            "type": "String"
          },
        }
      ]
    }
  ]
}
```

```
import (
    null_v4 "gopkg.in/guregu/null.v4"
)

type test struct {
    columnOne null_v4.String
}
```

**Closed** 2020-11-15 04:09 UTC
Labels: bug
