### ISSUE TITLE
mysql sum returned as interface{} instead of int

### ISSUE THREAD

**Issue by roccoblues** [kyleconroy/sqlc#1418] opened 2022-02-07 09:47 UTC
### Version

1.12.0

### What happened?

The `sum` returned from this simple query `SELECT SUM(books) FROM authors` is of type `interface{}` but should be some `int`. We currently workaround that issue with this query `SELECT SUM(books)*1 FROM authors`.

### Database schema

```sql
CREATE TABLE authors (
  id    BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name  text    NOT NULL,
  books int(10) UNSIGNED NOT NULL
);
```

### SQL queries

```sql
SELECT SUM(books) FROM authors;
```

### Playground URL

https://play.sqlc.dev/p/176d1b4765f4d78b2b2bad5e948ec74b77dacf4b05e87a0f8eaa11462b5fae20

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment] 2022-03-19 02:42
Duplicate of #1450

**Closed by kyleconroy** 2022-03-19 02:42 UTC
Labels: bug, triage
