### ISSUE TITLE
Forgotten import of "time" in .sql.go file

### ISSUE THREAD

**Issue by janiskemper** [kyleconroy/sqlc#1034] opened 2021-05-26 10:17 UTC
The generated .sql.go file does not import "time" when necessary. When having a select statement returning an object which is not defined already in models.go and containing a time.Time value, then this leads to an error. 

I have the sqlc-dev version v1.7.1-devel

Any ideas?

**Comment by kyleconroy** [comment] 2021-08-10 17:51
@janiskemper Can you provide a complete example? I'm not able to reproduce this myself.

**Comment by janiskemper** [comment] 2021-08-11 12:48
I have had some further insights in this and I would say that the inputs works well for models.go. If there are some special inputs in the objects like ListExampleRow, which do not correspond to any database table and which do not get defined in models.go but in the same files as the functions, then there are inputs missing. But this is not only time, but several other "third-party inputs". But I didn't really find a pattern there, because sometimes it does work.

**Comment by kyleconroy** [comment] 2021-08-11 13:44
@janiskemper Can you please provide a schema and query that causes the issue? Otherwise I'm going to have to close this out.

**Closed** 2021-08-20 07:52 UTC
Labels: invalid
