### ISSUE TITLE
Support crawshaw.io/sqlite?

### ISSUE THREAD

**Issue by josharian** [kyleconroy/sqlc#405] opened 2020-03-13 21:58 UTC
I’d love to use sqlc. I’d need to do an incremental migration to it, though, and my existing codebase uses https://godoc.org/crawshaw.io/sqlite for sqlite.

So I thought I’d suggest it as a possible feature, if it fits ok into the existing code infrastructure.

Unfortunately I can’t realistically volunteer to do the work...so this is me being one of Those People. Sorry. And thanks!

**Comment by thepudds** [comment] 2020-11-27 18:25
Hi @josharian, just a quick comment in case you had not yet seen #161, including https://github.com/kyleconroy/sqlc/issues/161#issuecomment-565569034, which mentions a parser is likely largest blocker, as well as follow-up about possibly using ANTLR for the parsing in 
https://github.com/kyleconroy/sqlc/issues/161#issuecomment-584407615. 

In any event, I realize you have a more specific issue here, but wanted to at least link the issues.

**Comment by thepudds** [comment] 2020-11-27 18:44
And... catching myself up, there is also https://github.com/kyleconroy/sqlc/pull/331

But I will stop there, given I believe you in fact know how to use GitHub 😄

**Comment by josharian** [comment] 2020-11-27 18:46
modernc.org/sqlite is a Go sqlite port, which presumably contains a SQLite parser. :) Maybe it could be extracted and reused?

**Comment by kyleconroy** [comment] 2021-08-28 20:39
Closing as a duplicate of #161

**Closed by kyleconroy** 2021-08-28 20:39 UTC
