### ISSUE TITLE
lib/pq is deprecated

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#470] opened 2020-04-30 22:17 UTC
The authors of the [lib/pq](https://github.com/lib/pq) library are encouraging new projects to use pgx instead:

> This package is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using pgx which is actively maintained.

At the very least sqlc should probably provide the option to use that project.

**Comment by kyleconroy** [comment] 2020-04-30 23:57
Huh.

Looks like we have our first issue for v1.4.0

**Comment by tv42** [comment] 2020-07-14 23:53
Can this be marked as duplicate of #472 and closed?

**Closed** 2021-08-13 03:36 UTC
Labels: enhancement
