### ISSUE TITLE
Wrong param name and type when using NULLIF

### ISSUE THREAD

**Issue by said-saifi** [kyleconroy/sqlc#936] opened 2021-03-11 07:09 UTC
## Summary
When using NULLIF in an UPDATE query then the field in the Params struct comes as 

```
Column2 interface{}
```
## Version
v1.6.0

## How to reproduce?

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);

-- name: UpdateAuthor :exec
UPDATE authors
SET name=NULLIF($2, '') WHERE id=$1;
```

Or [click here](https://play.sqlc.dev/p/7721b5477d028c0f0405bce45f809b7dd53ae59bf67f88420880efdba140f7c3)

## Expected Result

```go
type UpdateAuthorParams struct {
	ID      int64
	Name    string
}
```

## Actual Result
```go
type UpdateAuthorParams struct {
	ID      int64
	Column2 interface{}
}
```
## Possible Alternatives
If your column is nullable (no `NOT NULL`) then you can use `COALESCE` as [shown here.](https://play.sqlc.dev/p/66d60d211804a0f59a363264b87e4479e3234fef5a905306efe81d191b4a5d79)

Note that if your column is `NOT NULL`  in the database, then there is an [open issue](https://github.com/kyleconroy/sqlc/issues/937) and `COALESCE` may not work.

**Comment by idirall22** [comment] 2021-03-14 08:17
@said-saifi 
use named variables not dollar signs and cast the name to varchar.

```
-- name: UpdateAuthor :exec
UPDATE authors
SET name=NULLIF(@name::varchar, '') WHERE id= @id;
```

**Comment by kyleconroy** [comment] 2021-09-12 23:52
Duplicate of https://github.com/kyleconroy/sqlc/issues/133

**Closed by kyleconroy** 2021-09-12 23:52 UTC
