### ISSUE TITLE
Can we make WithTx input params as interface{}? 

### ISSUE THREAD

**Issue by elvizlai** [kyleconroy/sqlc#1502] opened 2022-03-22 00:40 UTC
### What do you want to change?

for change generated code, `WithTx(tx *sql.Tx) *Queries`, can we change *sql.Tx same as `DBTX` or other related interface?

### What programming language backends need to be changed?

Go

**Comment by elvizlai** [comment] 2022-05-01 14:59
@kyleconroy PTAL

**Comment by danielbprice** [comment] 2022-08-18 16:13
@elvizlai, this may be a duplicate of #383.  There are some solutions illustrated there.

**Closed** 2022-08-29 02:41 UTC
Labels: enhancement, triage
