### ISSUE TITLE
mysql engine, field json_tags_case_style not found in type config.v1PackageSettings 

### ISSUE THREAD

**Issue by mgyong** [kyleconroy/sqlc#962] opened 2021-04-01 17:18 UTC
sqlc version: v1.7.0
```
sqlc generate
error parsing sqlc.yaml: yaml: unmarshal errors:
  line 13: field json_tags_case_style not found in type config.v1PackageSettings

```
Below is my sqlc.yaml
```
version: "1"
packages:
- name: "sqldb"
  path: "repo/sqldb"
  queries: "./config/sql/queries/"
  schema: "./config/sql/schema/"
  engine: "mysql"
  emit_prepared_queries: false
  emit_interface: true
  emit_exact_table_names: false
  emit_empty_slices: false
  emit_json_tags: true
  json_tags_case_style: "pascal"
````

**Comment by kyleconroy** [comment] 2021-04-07 00:47
Duplicate of #946 

https://github.com/kyleconroy/sqlc/issues/946#issuecomment-803261209

**Closed by kyleconroy** 2021-04-07 00:47 UTC
Labels: invalid
