### ISSUE TITLE
Missing import for overrides

### ISSUE THREAD

**Issue by tschaub** [kyleconroy/sqlc#2304] opened 2023-06-07 15:38 UTC
### Version

1.18.0

### What happened?

I upgraded from `v1.12.0` to `v1.18.0` and see that the generated code no longer includes imports for overrides in my `sqlc.yaml`.

Here is an example change in one of the generated files after upgrading:
```diff
diff --git a/gen/queries/publications.sql.go b/gen/queries/publications.sql.go
index 1b22458..c3d0253 100644
--- a/gen/queries/publications.sql.go
+++ b/gen/queries/publications.sql.go
@@ -1,4 +1,6 @@
 // Code generated by sqlc. DO NOT EDIT.
+// versions:
+//   sqlc v1.18.0
 // source: publications.sql
 
 package queries
@@ -8,7 +10,6 @@ import (
        "encoding/json"
        "time"
 
-       "example.com/mod/geo"
        "github.com/google/uuid"
        "github.com/lib/pq"
 )
```

### Database schema

```sql
CREATE TABLE publications (
	id UUID PRIMARY KEY,
	title TEXT NOT NULL,
	abstract TEXT NOT NULL,
	publisher TEXT NOT NULL,
	date_published TIMESTAMP WITH TIME ZONE NOT NULL,
	geometry GEOMETRY NOT NULL,
	created TIMESTAMP WITH TIME ZONE NOT NULL,
	updated TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ON publications USING GIST(geometry);
CREATE INDEX ON publications USING GIN(vector);
CREATE INDEX ON publications (created DESC);
```

### SQL queries

```sql
-- name: CreatePublication :one
INSERT INTO publications (
  id, title, abstract, type, publisher, date_published, published, geometry, created, updated
) VALUES (
  sqlc.arg('id'),
  sqlc.arg('title'),
  sqlc.arg('abstract'),
  sqlc.arg('type'),
  sqlc.arg('publisher'),
  sqlc.arg('date_published'),
  sqlc.arg('published'),
  sqlc.arg('geometry'),
  sqlc.arg('created'),
  sqlc.arg('updated')
)
RETURNING *;
```

### Configuration

```yaml
version: "1"
packages:
  - name: "queries"
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: true
    path: "gen/queries"
    schema: "./sql/schema/"
    queries: "./sql/queries/"
overrides:
  - db_type: "geometry"
    go_type: "*example.com/mod/geo.Geometry"
```

### Playground URL

https://play.sqlc.dev/p/5677f36f5aafd936d7732c20ed2e0ed5bde9fb90fa6906d12477e00ea5c5143f

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by andrewmbenton** [comment] 2023-06-19 05:34
Based on my testing I am seeing the correct imports when running a sqlc build from the main branch, which means it should be resolved with the next release.

I have turned this example into an endtoend test and will work on getting it added so that we catch this in the future.

**Comment by andrewmbenton** [comment] 2023-06-20 18:44
After further inspection I believe the tests in [internal/endtoend/testdata/overrides_pointers](https://github.com/kyleconroy/sqlc/tree/3b21fdf547b0b80078d41c99b928807f9dabfb88/internal/endtoend/testdata/overrides_pointers) cover this. Those tests were introduced just after the last release.

So I think this is a duplicate of https://github.com/kyleconroy/sqlc/issues/2239. I will close for now but if you see this persist with either a build from main or after the next release please reopen.

**Closed by andrewmbenton** 2023-06-20 18:44 UTC
Labels: bug, regression, :books: postgresql, :wrench: golang, :computer: darwin

**Comment by stepan-romankov** [comment] 2023-07-10 12:12
Bug is still present
