### ISSUE TITLE
How does this work for bulk operations?

### ISSUE THREAD

**Issue by matheuscscp** [kyleconroy/sqlc#216] opened 2019-12-25 18:37 UTC
Imagine my program receives a list of Book unique keys, and it needs to return the list of these Books. The query would be something like this:

```sql
SELECT * FROM books WHERE key IN ('key1', ..., 'keyN');
```

How would I use sqlc for that?

**Comment by kyleconroy** [comment] 2019-12-25 19:24
You're in luck! sqlc already supports this using [`ANY`](https://github.com/kyleconroy/sqlc/blob/master/examples/any.md). The following SQL:

```
-- name: GetBulkBooks :many
SELECT * FROM books
WHERE key = ANY($1::text[]);
```

generate this method signature

```
func (q *Queries) GetBulkBooks(ctx context.Context, keys []string) ([]Book, error) {
  ...
}
```

Duplicate of #167

**Closed by kyleconroy** 2019-12-25 19:24 UTC
Labels: duplicate

**Comment by matheuscscp** [comment] 2019-12-25 19:38
Sorry for not being specific enough: What about bulk inserts?

**Comment by kyleconroy** [comment] 2019-12-25 21:35
There are a few ways to do bulk inserts in Go. [This article](https://medium.com/@amoghagarwal/insert-optimisations-in-golang-26884b183b35) from 2017 goes into two approaches. The first approach, insering multiple records inside a transaction, can be used today with sqlc. 

```sql
-- name: InsertBook :exec
INSERT INTO books (key, title) VALUES ($1, $2)
```

However, this isn't really a true bulk insert. You can insert multiple records in a single query:

```sql
-- name: BulkInsert :exec
INSERT INTO books (key, title) VALUES
    ($1, $2),
    ($3, $4),
    ($5, $6)
```

This approach can't support a dynamic number of records.

The [suggested approach](https://www.postgresql.org/docs/current/populate.html) is to use COPY (see this excellent [StackOverflow answer](https://stackoverflow.com/questions/758945/whats-the-fastest-way-to-do-a-bulk-insert-into-postgres)). `lib/pq` has [special support](https://godoc.org/github.com/lib/pq#hdr-Bulk_imports) for this use case. I've opened up #218 for the feature.

**Comment by BienTrinh** [comment] 2020-08-30 16:04
It does not work on MySQL.  My table and schema below:
schema:
CREATE TABLE `pkg` (
        `id` text NOT NULL,
        `vic` VARCHAR(50) NOT NULL,
        `kim` text NOT NULL,
        `order` INTEGER NOT NULL,
        PRIMARY KEY (`id`)
);
/* name: GetPkgID :many */
SELECT `id`,`vic`,`kim` FROM `pkg` WHERE `vic` = ANY($1::int[]) AND `shop_id` = ?;

sqlc generate
sql/query/pkg.sql:2:67: syntax error at or near "$"
sql/query/pkg.sql:2:76: syntax error at or near "]"

**Comment by kyleconroy** [comment] 2020-08-30 17:57
MySQL does not support arrays so it's not expected for this to work. I've opened #695 to track this issue.
