### ISSUE TITLE
Array of nullable items in aggregates

### ISSUE THREAD

**Issue by Yamakaky** [kyleconroy/sqlc#1413] opened 2022-02-04 14:16 UTC
### Version

1.11.0

### What happened?

Lets say I want to run this request:
```sql
create table sometable (
  key text not null,
  value text
);
select key, array_agg(value)::text[] from sometable group by key;
```
`sqlc` will generate a struct like this:
```go
type QueryRow struct {
	Key   text
	Value []string
}
```
However, some values may be `null`, which will fail with a scan error. Is there a way to tell sqlc to generate `Value []sql.NullString`?

### Database schema

```sql
create table sometable (
  key text not null,
  value text
);
```

### SQL queries

```sql
select key, array_agg(value)::text[] from sometable group by key;
```

**Comment by kyleconroy** [comment] 2022-02-04 16:09
Duplicate of https://github.com/kyleconroy/sqlc/issues/185

**Closed by kyleconroy** 2022-02-04 16:09 UTC
Labels: bug, triage

**Comment by Yamakaky** [comment] 2022-02-05 15:15
Wow, my bad, I missed that one
