### ISSUE TITLE
MySQL: Unsupported Scan with datetime field type

### ISSUE THREAD

**Issue by gpontesss** [kyleconroy/sqlc#575] opened 2020-07-01 20:25 UTC
I have a datetime fielld in my table. When I try to query a single row with it, the following error is returned:

```
Scan error on column index 8, name "created_at": unsupported Scan, storing driver.Value type []uint8 into type *time.Time
```

Sample table:

```
CREATE TABLE my_table (
    id INT(11) NOT NULL AUTO_INCREMENT,
    created_at datetime(6) NOT NULL,
    value VARCHAR(16),
)
```

Sample query:

```
/* name: GetMyRow :one */
SELECT *
FROM my_table
WHERE my_table.id = ?
LIMIT 1;
```

**Comment by kyleconroy** [comment] 2020-08-25 23:02
You'll need to set the parseTime parameter to true. See [this answer](https://stackoverflow.com/questions/29341590/how-to-parse-time-from-database/29343013#29343013) on StackOverflow.

Duplicate of #440

**Closed by kyleconroy** 2020-08-25 23:02 UTC
Labels: bug, mysql
