### ISSUE TITLE
NULLIF not working for enum values

### ISSUE THREAD

**Issue by amckinney** [kyleconroy/sqlc#752] opened 2020-10-28 21:28 UTC
I was exploring workarounds related to https://github.com/kyleconroy/sqlc/issues/374, and attempted to use the `NULLIF` function for an `enum` in my `SELECT` query, but noticed it wasn't working according to my expectation.

I created a reproducible example in a [playground](https://play.sqlc.dev/p/f5d4e3c89a940fb499399a0eae53d3181ad289124a82f82b98a7e86e9c802b4c). In this case, I'm attempting to use `NULLIF` so that I can handle `nil` values for the `role`. Instead, the generated code turns the expected value for a `role` into a `bool`.

**Comment by kyleconroy** [comment] 2021-09-12 23:52
Duplicate of https://github.com/kyleconroy/sqlc/issues/133

**Closed by kyleconroy** 2021-09-12 23:52 UTC
