### ISSUE TITLE
Not fully implemented materialized view.

### ISSUE THREAD

**Issue by alexuserid** [kyleconroy/sqlc#831] opened 2020-12-15 14:22 UTC
I made materialized view creation requests into schema.sql file, and it's fine. But when I try to make select query for the materizlized view, I have an error during execution `generate` command: `relation "materialized_view_name" does not exist`.
Also query which refreshes material view has no go code after generation.

**Comment by johanbrandhorst** [comment] 2021-01-11 16:00
Potentially dupe of https://github.com/kyleconroy/sqlc/issues/193?

**Comment by kyleconroy** [comment] 2021-01-25 07:30
Indeed, making this a duplicate

**Closed** 2021-01-25 07:31 UTC
